apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudx-rolebinding
  namespace: cloudx-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudx-role
subjects:
- kind: ServiceAccount
  name: controller-sa
  namespace: cloudx-system