
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cloudx-role
  namespace: cloudx-system
rules:
- apiGroups:
  - commons.cloudx.io
  resources:
  - sharedinfras
  - executions
  - connectioninterfaces
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - commons.cloudx.io
  resources:
  - sharedinfras/finalizers
  verbs:
  - update
- apiGroups:
  - commons.cloudx.io
  resources:
  - sharedinfras/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch