FROM node:20-alpine3.17 as build-stage
WORKDIR /app
COPY ui/package*.json /app/
RUN npm install
COPY ui/ /app/
RUN npm run build

# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:1.24
#Copy ci-dashboard-dist
COPY --from=build-stage /app/dist/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx-custom.conf /etc/nginx/conf.d/default.conf
#Copy default nginx configuration
# COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf