FROM golang:1.20 AS build-stage

WORKDIR /app

# COPY go.mod go.sum ./

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /job-bin cmd/runner/main.go

# Run the tests in the container
# FROM build-stage AS run-test-stage
# RUN go test -v ./...

# Deploy the application binary into a lean image
FROM alpine AS build-release-stage

WORKDIR /

COPY --from=build-stage /job-bin /job-bin

# EXPOSE 8080

# USER nonroot:nonroot

ENTRYPOINT ["/job-bin"]