apiVersion: v1
kind: Service
metadata:
  name: cloudx-apiserver
  labels:
    app.kubernetes.io/name: cloudx-apiserver
    app.kubernetes.io/part-of: cloudx
    app.kubernetes.io/component: apiserver
spec:
  selector:
    app.kubernetes.io/name: cloudx-apiserver
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080