apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: cloudx-apiserver
    app.kubernetes.io/part-of: cloudx
    app.kubernetes.io/component: apiserver
  name: cloudx-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudx-apiserver
subjects:
- kind: ServiceAccount
  name: cloudx-apiserver
  namespace: cloudx-system