apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudx-apiserver
  labels:
    app.kubernetes.io/name: cloudx-apiserver
    app.kubernetes.io/part-of: cloudx
    app.kubernetes.io/component: apiserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudx-apiserver
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudx-apiserver
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - /usr/local/bin/apiserver
        image: mayconjrpacheco/cloudx:latest
        name: apiserver
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      serviceAccountName: cloudx-apiserver
      terminationGracePeriodSeconds: 10