apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cloudx-apiserver
    app.kubernetes.io/part-of: cloudx
    app.kubernetes.io/component: apiserver
  name: cloudx-apiserver