apiVersion: commons.cloudx.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-config
spec:
  type: AWS
  source: ENV
  secretRef:
    name: aws-creds
    namespace: default
  awsConfig:
    region: 'us-east-1'