apiVersion: commons.cloudx.io/v1alpha1
kind: SharedInfra
metadata:
  name: demo-1
  labels:
    revision: 0.0.1
spec:
  author: Maycon Pacheco
  description: SharedInfra for example 2
  providerConfigRef:
    name: aws-config
    namespace: default
  plugins:
  - name: demo-1-sns
    ref: mayconjrpacheco/plugin:sns-1
    depends: []
    type: terraform
    outputs: []
    inputs:
    - key: name
      value: my-topic-1
    - key: region
      value: us-east-1

  - name: demo-1-lambda-role
    ref: mayconjrpacheco/plugin:lambda-role-1
    depends: []
    type: terraform
    outputs: []
    inputs:
    - key: lambda_name
      value: demo-1-function
    - key: region
      value: us-east-1

  - name: demo-2-sns
    ref: mayconjrpacheco/plugin:sns-1
    depends:
    - demo-1-sns
    - demo-1-lambda-role
    type: terraform
    outputs: []
    inputs:
    - key: name
      value: my-topic-2
    - key: region
      value: us-east-1






