apiVersion: commons.cloudx.io/v1alpha1
kind: SharedInfra
metadata:
  name: stackset-1
spec:
  author: Maycon Pacheco
  description: SharedInfra for example 1
  plugins:
  - name: sqs
    ref: mayconjrpacheco/sqs:latest
    depends: []
    type: terraform
    inputs:
    - key: name
      value: celio
  - name: sqs-policy
    ref: mayconjrpacheco/sqs-policy:latest
    type: terraform
    depends: []
    inputs:
    - key: name
      value: santos