apiVersion: commons.cloudx.io/v1alpha1
kind: SharedInfra
metadata:
  name: stackset-1
spec:
  author: Maycon Pacheco
  description: SharedInfra for example 1
  # globalInputs:
  #   - key: name
  #     value: lg
  providerConfigRef:
    name: aws-config
    namespace: default
  plugins:
  - name: test-1
    ref: mayconjrpacheco/plugin:test-1
    depends: []
    type: terraform
    outputs: []
    inputs:
    - key: name
      value: test-1
    # inputs-envs:
  - name: test-2
    ref: mayconjrpacheco/plugin:sns-1
    type: terraform
    depends: 
    - test-1
    outputs: []
    inputs:
    - key: name
      value: "test-2-{{ test-1.outputs.uid }}"
