apiVersion: commons.cloudx.io/v1alpha1
kind: SharedInfra
metadata:
  name: stackset-1
  labels:
    revision: 0.0.3
spec:
  author: Maycon Pacheco
  description: SharedInfra for example 1
  providerConfigRef:
    name: aws-config
    namespace: default
  plugins:
  - name: test-1
    ref: mayconjrpacheco/plugin:test-1
    depends: []
    type: terraform
    outputs: []
    inputs:
    - key: name
      value: test-1



