apiVersion: commons.cloudx.io/v1alpha1
kind: SharedInfra
metadata:
  name: stackset-1
spec:
  author: Maycon Pacheco
  description: SharedInfra for example 1
  # globalInputs:
  #   - key: name
  #     value: lg
  plugins:
  - name: celio-1
    ref: mayconjrpacheco/celio-plugin:latest
    depends: []
    type: terraform
    outputs: []
    inputs:
    - key: name
      value: matheus
    # inputs-envs:
  - name: celio-2
    ref: mayconjrpacheco/celio-plugin:latest
    type: terraform
    depends: 
    - celio-1
    outputs: []
    inputs:
    - key: name
      value: joao
