apiVersion: commons.cloudx.io/v1alpha1
kind: SharedInfra
metadata:
  name: stackset-1
spec:
  author: Maycon Pacheco
  description: SharedInfra for example 1
  plugins:
  - name: sqs
    ref: mayconjrpacheco/celio-plugin:latest
    depends: []
    type: terraform
    outputs: []
    inputs:
    - key: name
      value: matheus
    inputs-envs:
      
  - name: sqs-policy
    ref: mayconjrpacheco/celio-plugin:latest
    type: terraform
    depends: []
    outputs: []
    inputs:
    - key: name
      value: leandro
