apiVersion: commons.cloudx.io/v1alpha1
kind: Infra
metadata:
  name: stackset-1
  labels:
    revision: 0.0.3
spec:
  author: Maycon Pacheco
  description: Infra for example 1
  providerConfigRef:
    name: aws-config
    namespace: default
  tasks:
  - name: test-1
    ref: mayconjrpacheco/task:test-1
    depends: []
    type: terraform
    outputs: []
    inputs:
    - key: name
      value: test-1



