apiVersion: v1
kind: Service
metadata:
  name: cloudx-controller
  labels:
    app.kubernetes.io/name: cloudx-controller
    app.kubernetes.io/part-of: cloudx
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: cloudx-controller
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudx-controller
  labels:
    app.kubernetes.io/name: cloudx-controller
    app.kubernetes.io/part-of: cloudx
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudx-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudx-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /usr/local/bin/controller
        args:
        - --leader-elect
        image: mayconjrpacheco/cloudx:latest
        name: controller
        ports:
        - containerPort: 9000
        env:
        - name: RPC_SERVER_ADDRESS
          value: "cloudx-controller.cloudx-system:9000"
        - name: ENV
          value: prod
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      serviceAccountName: cloudx-controller
      terminationGracePeriodSeconds: 10