apiVersion: v1
kind: Service
metadata:
  name: cloudx-ui
  labels:
    app.kubernetes.io/name: cloudx-ui
    app.kubernetes.io/part-of: cloudx
    app.kubernetes.io/component: ui
spec:
  selector:
    app.kubernetes.io/name: cloudx-ui
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080