apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/name: cloudx-ui
    app.kubernetes.io/part-of: cloudx
  name: cloudx-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: cloudx-ui
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/name: cloudx-ui
    app.kubernetes.io/part-of: cloudx
  name: cloudx-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudx-ui
    spec:
      containers:
      - image: mayconjrpacheco/cloudx-ui:latest
        imagePullPolicy: Always
        name: deploment-container-name
        ports:
        - containerPort: 80
