apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: cloudx-system
spec:
  selector:
    control-plane: cloudx-controller
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: cloudx-system
  labels:
    control-plane: cloudx-controller
spec:
  selector:
    matchLabels:
      control-plane: cloudx-controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: cloudx-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /controller
        args:
        - --leader-elect
        image: mayconjrpacheco/cloudx-controller:latest
        name: controller
        ports:
        - containerPort: 9000
        env:
        - name: RPC_SERVER_ADDRESS
          value: "controller.cloudx-system:9000"
        - name: ENV
          value: prod
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      serviceAccountName: controller-sa
      terminationGracePeriodSeconds: 10